[database]
connection_string = "postgres://root@localhost:26257/did?sslmode=disable"

[keys]
public = "aPublicKey"
secret = "aSecretKey"

[at]
context = "https://w3id.org/did/v1"

[app]
url = "http://localhost:5001"
port = ":5001"
