[database]
connection_string = "postgres://user@localhost:5432/did?sslmode=disable"

[keys]
public = "aPublicKey"
secret = "aSecretKey"

[at]
contextV1 = "https://w3id.org/did/v1"
contextV2 = "https://www.w3.org/ns/did/v1"

[app]
url = "http://localhost:5001"
port = ":5001"

[api_auth] # apiKey = apiSecret
"anAPIKey" = "anAPISecret"
"anotherAPIKey" = "anotherAPISecret"
