#!/usr/bin/env bash

set -e

cd "$( dirname "${BASH_SOURCE[0]}" )/.."
DATABASE_URL=`./scripts/db-url`

cat > ./tmp/db-dump.sql
./scripts/db-drop
./scripts/db-create
psql $DATABASE_URL < ./tmp/db-dump.sql
