#!/usr/bin/env bash

set -e

cd "$( dirname "${BASH_SOURCE[0]}" )/.."

ROOT="$( cd "$( dirname "$0" )" && cd .. && pwd )"

bail(){
  echo $1 1>&2;
  exit 1
}

[[ $DATABASE_URL && ${DATABASE_URL-x} ]] || bail 'DATABASE_URL is required'
[[ $URL && ${URL-x} ]] || bail 'URL is required'
[[ $PORT && ${PORT-x} ]] || bail 'PORT is required'
[[ $PUBLIC_KEY && ${PUBLIC_KEY-x} ]] || bail 'PUBLIC_KEY is required'
[[ $PRIVATE_KEY && ${PRIVATE_KEY-x} ]] || bail 'PRIVATE_KEY is required'
[[ $CONTEXT && ${CONTEXT-x} ]] || bail 'CONTEXT is required'

set -x

go get github.com/BurntSushi/toml
go get github.com/lib/pq
go get github.com/dgrijalva/jwt-go
go get golang.org/x/crypto/ed25519
go get golang.org/x/crypto/nacl/box
go get github.com/go-chi/chi
go get github.com/go-chi/chi/middleware
go get github.com/hashicorp/go-multierror

set +x

cat <<END_OF_CONFIG > $ROOT/test.config.toml
[database]
connection_string = "$DATABASE_URL"

[keys]
public = "$PUBLIC_KEY"
secret = "$PRIVATE_KEY"

[at]
context = "$CONTEXT"

[app]
url = "$URL"
port = ":$PORT"

[api_auth]
"74fb5cf4f8ce852e143e2859d61b7df5c6572edbbb580e71395d3266506face7" = "809d311ff23626ddf58297f3322f84ec2b0cedf1b2a38b3d456b39298db61820"
END_OF_CONFIG

./scripts/db-setup
